### ISSUE TITLE
Longer Active Timeout

### ISSUE THREAD

**Issue by wreck3d** [darsain/twitch-giveaways#11]
This is a request instead of an issue, but could you please set "No Timeout" or "Infinite" as an option for people who enter giveaways via keyword? Thanks!

**Comment by darsain** [comment]
I don't like cluttering the UI with features that will be used by 2 people :)

Besides, this project is pretty much in a maintenance only mode (bug fixing only), since I can't afford donating more time to it.

**Comment by wreck3d** [comment]
It wouldn't clutter the UI, it'd just be the next option on the slider next to "60."

Hm...is there a way I could get the code or something and manually do it?

**Comment by darsain** [comment]
:eyes: This very page is the repository with the source code.

**Comment by wreck3d** [comment]
Oh wow, haha. Sorry. I've been replying from my E-Mail.

**Comment by wreck3d** [comment]
Alright, so now, how would I edit the one part to make an "Infinite" option on the slider and then include that in the Chrome extension itself?

**Comment by MarshmallowBob** [comment]
Are you missing a marble or two, wrecked? He literally gives you the code and says the project is in maintenance mode and he's not doing feature requests, and now you ask him how to add it yourself? come on man.

**Comment by wreck3d** [comment]
Alright, maybe asking wasn't the right thing to do?
I was just trying to make it easier for him if I just did it for myself.
I know how to add the feature, I just don't know what specifically I need
to do with the Chrome extension.

On Thu, May 14, 2015 at 7:52 PM, MarshmallowBob <notifications@github.com>
wrote:

> Are you missing a marble or two, wrecked? He literally gives you the code
> and says the project is in maintenance mode and he's not doing feature
> requests, and now you ask him how to add it yourself? come on man.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/darsain/twitch-giveaways/issues/11#issuecomment-102203436>
> .
>



-- 
-Branden-

**Comment by darsain** [comment]
Well, before you can even start editing, you'd have to install a development environment: node + npm + gulp

Than clone the repo, edit required stuff, build the extension from source using build tasks defined in `gulpfile.js`, and load the result manually in Chrome. But you can't use stable version of chrome, you have to use beta or canary, otherwise it won't let you use developer extensions comfortably. And you have to use developer mode since I'm hardly gonna give you rights to publish into chrome web store.

It's not trivial stuff if you are completely oblivious to all of these things. And this is not a place to learn that :)

---

Alternative would be going directly into directory where chrome keeps unpacked extensions, opening the build js file, and edditing that. The issue with this is that built files are minified and obfuscated, so editing them is quite a pain. And all edits would get overridden when Chrome updates to the next TGA version (when I fix something in future for example).
