### ISSUE TITLE
No text?

### ISSUE THREAD

**Issue by PresidentSlendy** [darsain/twitch-giveaways#16]
The giveaway plugin for twitch does not have text on it's buttons anymore. I have reinstalled the plugin, chrome and restarted over 10 times. Still I get this bug.
Here it is:
![giveaway plugin fail](https://cloud.githubusercontent.com/assets/13947327/9444271/eb09c6c4-4a85-11e5-80d9-a81868dbb315.JPG)

**Comment by darsain** [comment]
Just tested it and everything works fine.

Maybe font failed to load. Or, since I see that your **Chat** button is rounded, it looks like you are applying additional styles (via another extension, or some CSS tweaking thingy) which might be colliding. It looks like those styles are setting the default text color to `transparent`.

I can't control any of the things that could be causing this for you, so I'm closing this issue, since it's not related to this extension.
