### ISSUE TITLE
Follower luck instead of Subscriber luck

### ISSUE THREAD

**Issue by green-big-frog** [darsain/twitch-giveaways#18]
It would be great if Followers also could get special treatment!

**Comment by darsain** [comment]
I can't implement it as I don't know who is following the channel beforehand. I'd have to query the whole followers list from twitch API, and compare it with current viewers list. That is not a trivial thing to do, would require people to constantly run updates which take time, and that would overly complicate the giveaway process.

That's why it's not in already.

When twitch implements some nice chat API which would allow me to get better info about people in it, feel free to reopen this issue.
