### ISSUE TITLE
Breaks with BTTV installed

### ISSUE THREAD

**Issue by EhsanKia** [darsain/twitch-giveaways#7]
It's opening fine now, and the GUI shows, but the names aren't coming into the list.
Looking at the console, there are these errors: http://i.imgur.com/Gwha2uq.png

There seems to be an issue with connecting to the IRC? Sometimes 1-2 names make it to the list but it breaks right away. Is this a temporary Twitch server issue?

**Comment by EhsanKia** [comment]
Any plans on fixing this? It's been broken for a few weeks now with BTTV.

**Comment by darsain** [comment]
As I've said. PITA to maintain compatibility with other extensions. Especially when they are changing DOM... seriously.

I'm glad I can find time to fix stuff when twitch changes something. I don't want to also do the same for extensions... That's too much to ask.

**Comment by darsain** [comment]
To nightwalker: the whole observing and parsing logic is isolated in [`src/js/lib/chat.js`](https://github.com/darsain/twitch-giveaways/blob/master/src/js/lib/chat.js).

It basically just attaches a `MutationObserver` on `.chat-room .chat-lines` element, and than parses changes like this:

```js
node = addedNodes[i];
line = node.querySelector && node.querySelector('.chat-line');
if (!line) continue;
name = query('.from', line);
name = name && name.textContent.trim();
if (!name) continue;
if (query('.deleted', line)) continue;
html = query('.message', line).innerHTML.trim();
text = textify(html);
chat.emit('message', {
	user: {
		name: name,
		badges: slice(query.all('.badge', line)).map(getGroups).filter(filterFalsy),
	},
	html: html,
	text: text,
	time: new Date()
});
```

Can you tell me how could BTTV interfere with this? What exactly is BTTV  doing to the chat elements?

**Comment by night** [comment]
This is an old issue, but we did change to support Twitch Giveaways a while ago. Only about a month ago did Twitch Giveaways stop working with BetterTTV, for reasons unknown to us.

This is our ```.chat-line```

    <div class="chat-line" data-sender="night">
        <span class="timestamp"><small>6:03</small></span>  
        <span class="badges"> 
            <div class="bttv-developer badge" title="NightDev Developer"></div> 
            <div class="turbo badge" title="Twitch Turbo"></div> 
            <div class="subscriber badge" title="Channel Subscriber"></div> 
        </span>
        <span style="color: #000000;" class="from">Night</span>
        <span class="colon">:</span>&nbsp;<wbr>
        <span class="message" data-raw="dom%20test" data-emotes="%7B%7D">dom test</span>
    </div>

The only differences are data tags, and our elements are divs, not list elements (since Twitch randomly changed to list elements a while ago [before the break of BetterTTV and Twitch Giveaways]).

**Comment by darsain** [comment]
@night yah, but what is BTTV doing to chat exactly? Are you parsing messages and than re-inserting them? Or is there a twitch API that emits chat messages, and you build your own chat from that?

If you build your own chat, you might be discarding the original `.chat-lines` element to which TGA is binding its MutationObserver to. So, when BTTV gets initiated after TGA, TGA is left with a dick in its hand and nothing to do :)

**Comment by night** [comment]
We don't delete ```.chat-lines```, so I have no idea why your watcher breaks. If you have take a look at your commits from about a month ago, you [modified your watcher](https://github.com/darsain/twitch-giveaways/commit/03d268045f9ed9908c9834002ead530f0052a501) which is when BetterTTV broke with your add-on.

BetterTTV just deletes all ```.chat-line``` elements, removes Twitch's on message event callback, and adds in our own event callback to take over the messages. We then append into ```.chat-lines```, rather than Twitch. We do not disturb the DOM around chat, so again, I have no idea why Twitch Giveaways breaks when it's already watching the container.

2.4.0 works fine: https://nightdev.com/i/ss-0dtVMg5VufetZzz3XI9mtQFrd.png

**Comment by darsain** [comment]
Seems fixed.
